table Calendar
	lineageTag: 5d7b1ab3-e85e-4d96-a842-3184fde29747
	dataCategory: Time

	column CalendarID
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		sourceProviderType: int
		lineageTag: 73b81816-16c2-464f-be53-a6d511781de8
		summarizeBy: none
		sourceColumn: CalendarID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isKey
		formatString: mmmm d\, yyyy
		isAvailableInMdx: false
		sourceProviderType: datetimeoffset
		lineageTag: 62a108c0-bd2a-4155-aea6-f7dc95c8f581
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Day
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 2eff7f12-3950-4b31-9ac2-8d02b933e062
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: c0a68cb2-52cd-48b6-b41a-ed9b076e42c4
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 256e4cf4-712d-4c1b-8ca4-6a3bedcf6648
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column MonthYearYYYYMM
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		sourceProviderType: bigint
		lineageTag: 08b883ef-b208-47cd-9a4d-5cbd026d20aa
		summarizeBy: none
		sourceColumn: MonthYearYYYYMM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 8167a83b-b998-4fd3-9d0a-2e840800aaf6
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition Calendar = m
		mode: directQuery
		queryGroup: KQL
		source =
				let
				    Source = AzureDataExplorer.Contents(Eventhouse_Cluster_URL, Database, "range Date from toscalar(Commits | where Date >= ago(" & Number.ToText(Days_Since_Filter) &  "d) | summarize min(Date)) to now() step 1d#(lf)| extend #(lf)    Day = dayofmonth(Date),#(lf)    Month = getmonth(Date),#(lf)    Year = getyear(Date),#(lf)    MonthName = case(#(lf)        getmonth(Date) == 1, ""January"",#(lf)        getmonth(Date) == 2, ""February"",#(lf)        getmonth(Date) == 3, ""March"",#(lf)        getmonth(Date) == 4, ""April"",#(lf)        getmonth(Date) == 5, ""May"",#(lf)        getmonth(Date) == 6, ""June"",#(lf)        getmonth(Date) == 7, ""July"",#(lf)        getmonth(Date) == 8, ""August"",#(lf)        getmonth(Date) == 9, ""September"",#(lf)        getmonth(Date) == 10, ""October"",#(lf)        getmonth(Date) == 11, ""November"",#(lf)        getmonth(Date) == 12, ""December"",#(lf)        ""Unknown""#(lf)    ),#(lf)    MonthYearYYYYMM = getyear(Date) * 100 + getmonth(Date),#(lf)    CalendarID = toint(format_datetime(Date, 'yyyyMMdd'))#(lf)| project CalendarID, Date, Day, Month, MonthName, MonthYearYYYYMM, Year", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"MonthName", "Month Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

