table Commits
	lineageTag: a75af6c0-44fb-4f4e-a03d-c76bd32fca71

	column Id
		dataType: int64
		isKey
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 94c45391-1571-40cb-85e1-2132ca949167
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column RepositoryId
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: nvarchar(max)
		lineageTag: 4082822f-a1d2-4a66-8f98-8d234015545b
		summarizeBy: none
		sourceColumn: RepositoryId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CommitId
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: nvarchar(max)
		lineageTag: a511db79-b496-4472-9c80-853d8a363292
		summarizeBy: none
		sourceColumn: CommitId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Branch Name'
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 7195670e-d74d-4832-b37c-56636446de56
		summarizeBy: none
		sourceColumn: Branch Name

		annotation SummarizationSetBy = Automatic

	column LogicalId
		dataType: string
		isHidden
		isAvailableInMdx: false
		sourceProviderType: nvarchar(max)
		lineageTag: dfcf9adf-20f0-4209-8e24-78b66d1769e1
		summarizeBy: none
		sourceColumn: LogicalId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Artifact Name'
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: cb08672a-a8e5-4df6-a7e4-7c2522961dac
		summarizeBy: none
		sourceColumn: Artifact Name

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: a1902c32-f844-405c-83bd-84afdf498d3e
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		formatString: General Date
		isAvailableInMdx: false
		sourceProviderType: datetimeoffset
		lineageTag: 0e88de4b-3928-41d8-b00d-ab525be9a847
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Committed By'
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 566b927d-4cd4-4e31-a14e-1c7e5f83fa45
		summarizeBy: none
		sourceColumn: Committed By

		annotation SummarizationSetBy = Automatic

	partition Commits = m
		mode: directQuery
		queryGroup: KQL
		source =
				let
				    // Connects to Azure Data Explorer and queries commits within filtered days
				    #"Retrieved Commits From ADX" = AzureDataExplorer.Contents(Eventhouse_Cluster_URL, Database, "Commits #(lf)| where Date >= ago(" & Number.ToText(Days_Since_Filter,"D",Culture) &"d)", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				    // Renames columns for improved readability
				    #"Renamed Columns For Readability" = Table.RenameColumns(#"Retrieved Commits From ADX",{{"ArtifactName", "Artifact Name"}, {"BranchName", "Branch Name"}, {"CommittedBy", "Committed By"}})
				in
				    #"Renamed Columns For Readability"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

